USE DataWarehouseAnalytics;
GO

-- [EDA] Magnitude Analysis: Comparing the measure values by categories to understand the importance for each category

-- Find the total customers by country
SELECT
	country,
	COUNT(customer_id) as total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Find the total customers by gender
SELECT
	gender,
	COUNT(customer_id) as total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- Find the total products by category
SELECT
	category,
	COUNT(product_id) as total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- What is the average costs in each category?
SELECT 
	category,
	AVG(cost) as average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC

-- What is the total revenue generated for each category?
SELECT 
	category,
	SUM(sales_amount) as total_revenue
FROM  gold.dim_products a
LEFT JOIN gold.fact_sales b
ON a.product_key = b.product_key
GROUP BY category
ORDER BY total_revenue DESC

-- Find total revenue generated by each customer
SELECT 
	a.customer_key,
	a.first_name,
	a.last_name,
	SUM(sales_amount) as total_revenue
FROM gold.dim_customers a
LEFT JOIN gold.fact_sales b
ON a.customer_key = b.customer_key
GROUP BY a.customer_key, a.first_name, a.last_name
ORDER BY total_revenue DESC

-- What is the distribution of sold items across countries?
SELECT 
	country,
	SUM(quantity) as total_sold_items
FROM gold.fact_sales a
JOIN gold.dim_customers c
ON a.customer_key = c.customer_key
GROUP BY country
ORDER BY total_sold_items DESC
